version: '3'

services:
  house-system-backend:
    build:
      context: .
#      args:
#        - HTTP_PROXY=http://localhost:7890
#        - HTTPS_PROXY=https://localhost:7890
      dockerfile: Dockerfile
      network: host
    image: hewo233/house-system-backend
    ports:
      - "8080:8080"
    volumes:
      - ./db/.env:/app/db/.env:ro
      - ./utils/OSS/.env:/app/utils/OSS/.env:ro
      - ./config/.admin:/app/config/.admin:ro
    restart: unless-stopped